const { chromium } = require("@playwright/test");
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
  await page.goto("http://localhost:3000/login");
  await page.fill('input[type="email"]', "demo@wanmusheng.com");
  await page.fill('input[type="password"]', "demo1234");
  await page.click('button[type="submit"]');
  await page.waitForLoadState("networkidle");
  const list = (await (await page.request.get("http://localhost:3000/api/scripts")).json()).data;
  await page.goto(`http://localhost:3000/creation/film-factory/${list[0].id}`);
  await page.waitForLoadState("networkidle");
  await page.waitForTimeout(1500);
  const tab = page.getByRole("tab", { name: /妆造库/ });
  console.log("tab count:", await tab.count());
  await tab.click();
  await page.waitForTimeout(1200);
  console.log("selected:", await page.getByRole("tab", { name: /妆造库/ }).getAttribute("aria-selected"));
  console.log("panel visible buttons:", await page.getByRole("button", { name: /生成造型图/ }).count());
  console.log("any 生成造型图 text:", await page.getByText(/生成造型图/).count());
  const tabs = await page.getByRole("tab").allTextContents();
  console.log("tabs:", tabs);
  await page.screenshot({ path: ".screenshots/debug-outfits-tab.png" });
  await browser.close();
})();
